name: Build and Push Docker image to GitHub Packages

# Trigger the workflow on release creation for the main branch:
on:
  release:
    types: [released]

jobs:
  docker_image_build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      ENV_APISIX_IMAGE_TAG_NAME: apisix
      ENV_OS_ARCH: amd64

    steps:
    # Checkout the repository:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Convert repository name to lowercase
      id: repo_name
      run: |
        echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # Log in to GitHub Docker Registry (GitHub Packages):
    - name: Log in to GitHub Docker Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Build the Docker image:
    - name: Build Docker image
      run: |
          docker build \
            -t ghcr.io/${{ env.repo }}:latest \
            --build-arg TARGETARCH=${{ env.ENV_OS_ARCH }} \
            --build-arg CODE_PATH=. \
            --build-arg ENTRYPOINT_PATH=./docker/debian-dev/docker-entrypoint.sh \
            --build-arg INSTALL_BROTLI=./docker/debian-dev/install-brotli.sh \
            --build-arg CHECK_STANDALONE_CONFIG=./docker/utils/check_standalone_config.sh \
            -f ./docker/debian-dev/Dockerfile .

    # Push the Docker image to GitHub Packages:
    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ env.repo }}:latest

    # Tag the Docker image with the release version:
    - name: Tag the Docker image with the release version
      run: docker tag ghcr.io/${{ env.repo }}:latest ghcr.io/${{ env.repo }}:${{ github.event.release.tag_name }}

    # Push the Docker image with the release version to GitHub Packages:
    - name: Push the Docker image with the release version to GitHub Packages
      run: docker push ghcr.io/${{ env.repo }}:${{ github.event.release.tag_name }}
